homekit:
  name: Home Assistant
  # !!! Switch to tower
  advertise_ip: !secret ip_phoenix
  port: 31063
  filter:
    include_domains:
      - light
      - switch
      - media_player
    include_entity_globs:
      - sensor.*_lumi_*
      - binary_sensor.*_lumi_*
    include_entities:
      - sensor.cpu_temperature
    exclude_entities:
      - switch.network_controller
  entity_config:
    media_player.ps4_pi:
      feature_list:
        - feature: on_off
