#http:
#  server_host: 0.0.0.0
#  trusted_proxies:
#    - !secret network_cluster
#    - !secret ip_tailscale_jyunmou
#    - !secret ip_tailscale_phoenix
#    - !secret ip_tailscale_leaf
#  use_x_forwarded_for: true
