alias: Low Battery Level Check
use_blueprint:
  # manually import thru Settings -> Automations & Scences ->Blueprints
  path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
  input:
    actions:
      - service: shell_command.ntfy
        alias: Send ntfy.sh
        data_template:
          tags: house_with_garden
          topic: 家
          title: Battery Level Check
          message: >
            :zap: Low battery level for sensors: {{ sensors | replace(' battery state', '') }}.
